version: '2'
services:
  php-web:
    container_name: php-web
    image: centos-phpfpm-nginx:1.0
    ports:
      - 3000:80
    restart: always
    volumes:
      - "../php-web:/var/www/html"
    working_dir: /var/www/html
